name: Calls a script

on: workflow_call

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: run-the-script
      run: |
        node ./src/callable-script.js
